// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxfq8m4UqAQcaUv6q6s20k__emF2p_-xg',
    appId: '1:682301664838:web:00599bab72b75b4162e447',
    messagingSenderId: '682301664838',
    projectId: 'dmpportfolioapp',
    authDomain: 'dmpportfolioapp.firebaseapp.com',
    storageBucket: 'dmpportfolioapp.firebasestorage.app',
    measurementId: 'G-H2FEWQZF3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRP9i-J0xkc6EcP84vzYm8-JzRJ40wQ4o',
    appId: '1:682301664838:android:21ec7ea1e3b5ef6862e447',
    messagingSenderId: '682301664838',
    projectId: 'dmpportfolioapp',
    storageBucket: 'dmpportfolioapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC75HZgXidyX4OtvnBnLgzG7Gglkarx6aE',
    appId: '1:682301664838:ios:521d72a9d741dc2062e447',
    messagingSenderId: '682301664838',
    projectId: 'dmpportfolioapp',
    storageBucket: 'dmpportfolioapp.firebasestorage.app',
    iosBundleId: 'com.example.dmpportfolioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC75HZgXidyX4OtvnBnLgzG7Gglkarx6aE',
    appId: '1:682301664838:ios:521d72a9d741dc2062e447',
    messagingSenderId: '682301664838',
    projectId: 'dmpportfolioapp',
    storageBucket: 'dmpportfolioapp.firebasestorage.app',
    iosBundleId: 'com.example.dmpportfolioapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxfq8m4UqAQcaUv6q6s20k__emF2p_-xg',
    appId: '1:682301664838:web:ddec0e6bc6dc05fb62e447',
    messagingSenderId: '682301664838',
    projectId: 'dmpportfolioapp',
    authDomain: 'dmpportfolioapp.firebaseapp.com',
    storageBucket: 'dmpportfolioapp.firebasestorage.app',
    measurementId: 'G-1DQ7BFZNP8',
  );
}
